apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-demo.fullname" . }}-app-config
  labels:
    {{- include "devops-demo.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "devops-demo.postgresql.fullname" . | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  PORT: {{ .Values.backend.env.port | toString | quote }}
  CORS_ORIGIN: {{ .Values.backend.env.corsOrigin | quote }}
