apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-demo.fullname" . }}-app-secrets
  labels:
    {{- include "devops-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  DB_PASSWORD: {{ include "devops-demo.dbPassword" . | quote }}
