{{- if and .Values.backend.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "devops-demo.backend.fullname" . }}
  labels:
    {{- include "devops-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      {{- include "devops-demo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
