{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-demo.postgresql.fullname" . }}
  labels:
    {{- include "devops-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.postgresql.port }}
      targetPort: postgres
      name: postgres
  selector:
    {{- include "devops-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
